// @ts-nocheck -- skip type checking
import * as d_docs_7 from "../content/docs/reference/structural_elements/index.mdx?collection=docs"
import * as d_docs_6 from "../content/docs/reference/elements/table.mdx?collection=docs"
import * as d_docs_5 from "../content/docs/reference/elements/index.mdx?collection=docs"
import * as d_docs_4 from "../content/docs/reference/index.mdx?collection=docs"
import * as d_docs_3 from "../content/docs/advanced_usage/index.mdx?collection=docs"
import * as d_docs_2 from "../content/docs/advanced_usage/custom_title_template.mdx?collection=docs"
import * as d_docs_1 from "../content/docs/index.mdx?collection=docs"
import * as d_docs_0 from "../content/docs/guide.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"guide.mdx","fullPath":"content/docs/guide.mdx"}, data: d_docs_0 }, { info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: d_docs_1 }, { info: {"path":"advanced_usage/custom_title_template.mdx","fullPath":"content/docs/advanced_usage/custom_title_template.mdx"}, data: d_docs_2 }, { info: {"path":"advanced_usage/index.mdx","fullPath":"content/docs/advanced_usage/index.mdx"}, data: d_docs_3 }, { info: {"path":"reference/index.mdx","fullPath":"content/docs/reference/index.mdx"}, data: d_docs_4 }, { info: {"path":"reference/elements/index.mdx","fullPath":"content/docs/reference/elements/index.mdx"}, data: d_docs_5 }, { info: {"path":"reference/elements/table.mdx","fullPath":"content/docs/reference/elements/table.mdx"}, data: d_docs_6 }, { info: {"path":"reference/structural_elements/index.mdx","fullPath":"content/docs/reference/structural_elements/index.mdx"}, data: d_docs_7 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"pages":["index","guide","reference","advanced_usage","..."]}}, {"info":{"path":"advanced_usage/meta.json","fullPath":"content/docs/advanced_usage/meta.json"},"data":{"title":"Продвинутое использование","defaultOpen":true}}, {"info":{"path":"reference/meta.json","fullPath":"content/docs/reference/meta.json"},"data":{"title":"Справка","defaultOpen":true}}, {"info":{"path":"reference/elements/meta.json","fullPath":"content/docs/reference/elements/meta.json"},"data":{"title":"Элементы","description":"В этом разделе мы рассмотрим все элементы, которые можно использовать в шаблоне.","defaultOpen":true}}, {"info":{"path":"reference/structural_elements/meta.json","fullPath":"content/docs/reference/structural_elements/meta.json"},"data":{"title":"Структурные элементы","defaultOpen":true}}])